pipeline:

  test:
    image: bash:4.4
    commands:
      - ls -la
      - ls -la shelltests
      - cd shelltests
      - sh tests.sh
    when:
      event: [push, pull_request, tag]

  build_docker_image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - cd shelltests
      - ./tests.sh
      - cd ..
      - docker build -t docker-pttg-rds-tools .
    when:
      event: [push, pull_request, tag]

  tag_latest:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+docker_pttg_rds_tools" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag docker-pttg-rds-tools quay.io/ukhomeofficedigital/docker-pttg-rds-tools:build-$${DRONE_BUILD_NUMBER}
      - docker tag docker-pttg-rds-tools quay.io/ukhomeofficedigital/docker-pttg-rds-tools:latest
      - docker push quay.io/ukhomeofficedigital/docker-pttg-rds-tools:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/docker-pttg-rds-tools:latest
    when:
      event: push
      branch: [master]

  tag_version:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+docker_pttg_rds_tools" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag docker-pttg-rds-tools quay.io/ukhomeofficedigital/docker-pttg-rds-tools:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/docker-pttg-rds-tools:$${DRONE_TAG}
    when:
      event: tag
